### ISSUE TITLE
Error:Execution failed for task ':app:processDebugResources'. > com.android.ide.common.process.ProcessException: Failed to execute aapt

### ISSUE THREAD

**Issue by iostyle** [SiberiaDante/CustomDialog#1]
Error:(15, 21) No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

**Comment by iostyle** [comment]
解决方法:COMPILE_SDK_VERSION>=26

**Comment by iostyle** [comment]
还有不得不吐槽的地方，index竟然是从1开始

**Comment by SiberiaDante** [comment]
感谢大神提醒，已经修改过来了，以后的版本会提交的
